# Dependencies
# - markdown:         redcarpet
highlighter:      rouge

# Permalinks
# - permalink:        pretty
# - relative_permalinks: true

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

title: "Alex Claman"
tagline: ""
description: "Follow <a href=\"https://micro.blog/aclaman\">@aclaman on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/aclaman\">@aclaman on Micro.blog</a>."
baseurl: ""
url: "http://micro.alexclaman.com"
markdown: "kramdown"
username: "aclaman"
microblog_user: "aclaman"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Alex Claman"
name: "Alex Claman"
gravatar_hash: "cf2d3abdd0700f6a2a6e1c56e1a0d707"
avatar: "https://micro.blog/aclaman/avatar.jpg"
full_name: "Alex Claman"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Pacific-New"
site_id: "3928"
gems: ["jekyll-paginate"]
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Alex Claman"